In [1]:
import numpy as np
import matplotlib as plt


In [2]:
data = np.random.randn(2,3)
data


array([[ 1.11180781, -1.20684678, -0.05154691],
       [-0.71108087,  0.28400852, -1.97146267]])

In [3]:
data*10

array([[ 11.11807813, -12.06846776,  -0.51546906],
       [ -7.11080866,   2.8400852 , -19.71462666]])

In [4]:
data + data

array([[ 2.22361563, -2.41369355, -0.10309381],
       [-1.42216173,  0.56801704, -3.94292533]])

## Creating ndarrays


Convert from lists to numpy array.

In [5]:
data1 = [4, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [6]:
arr1


array([ 4. ,  7.5,  8. ,  0. ,  1. ])

In [7]:
# 2 Dimensional Arrays
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2) 

In [8]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)


2
(2, 4)
int64


In [10]:
# Zero array
zeros = np.zeros((3,6) )
zeros

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [11]:
empty_array = np.empty((2,3,2))
empty_array

array([[[ -0.00000000e+000,  -0.00000000e+000],
        [  2.96439388e-323,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[ -0.00000000e+000,  -0.00000000e+000],
        [  3.88497375e+097,   1.38400788e-047],
        [  5.82630726e-144,   9.73468728e-309]]])

In [12]:
ordered_array = np.arange(15)
ordered_array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Arithmatic with ndarrays

In [13]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])


In [14]:
arr*arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [15]:
arr ** 2

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [16]:
arr ** .5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [17]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr2)
arr2 > arr

[[  0.   4.   1.]
 [  7.   2.  12.]]


array([[False,  True, False],
       [ True, False,  True]], dtype=bool)

## Array Slices and indexing


In [18]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print (arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [19]:
# If an array or slice of an array is assigned to a variable, the variable points to the original object
# It is not a copy

array_slice = arr[5:8]
array_slice[1] = 555
print(arr)


[  0   1   2   3   4  12 555  12   8   9]
