## Julia notation for setting up arrays and some notations

In [1]:
random_array =  rand(2,3)
println(random_array)
println(random_array *10)
println(random_array + random_array)

[0.448841 0.45528 0.155436; 0.785553 0.290299 0.307912]
[4.48841 4.5528 1.55436; 7.85553 2.90299 3.07912]
[0.897683 0.910559 0.310872; 1.57111 0.580598 0.615824]


## Creating arrays. 

In [2]:
data1 = [4, 7.5, 8, 0, 1]
#arr1 = array(data1)

5-element Array{Float64,1}:
 4.0
 7.5
 8.0
 0.0
 1.0

In [3]:
println(data1)

[4.0, 7.5, 8.0, 0.0, 1.0]


### 2 Dimensional Arrays

In [4]:
data2 = [[1 2 3 4];[5 6 7 8]]

2×4 Array{Int64,2}:
 1  2  3  4
 5  6  7  8

In [5]:
println(ndims(data2)) # Dimensions
println(size(data2)) # Shape of the array/matrix
println(eltype(data2)) #data type of elements


2
(2, 4)
Int64


#### Calling the variable without a print statement returns the descriptive information, as well.  

In [6]:
data2

2×4 Array{Int64,2}:
 1  2  3  4
 5  6  7  8

#### Zero array

In [7]:
zeros_matrix = zeros(3,6)
println(zeros_matrix)
zeros_matrix

[0.0 0.0 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0 0.0]


3×6 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

#### Empty Array

In [8]:
empty_array = Array{Float64}(undef, (3, 2,2))
empty_array

3×2×2 Array{Float64,3}:
[:, :, 1] =
 2.28852e-314  2.28852e-314
 2.28852e-314  2.28852e-314
 2.28852e-314  2.29598e-314

[:, :, 2] =
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [9]:
ordered_array = Array(range(0, stop =14, step = 1))
println(ordered_array)



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


## Arithmatic with arrays

In [10]:
arr = [[1. 2. 3.];[4. 5. 6.]]

2×3 Array{Float64,2}:
 1.0  2.0  3.0
 4.0  5.0  6.0

In [11]:
arr.*arr # elementwise multiplcation operator is .*

2×3 Array{Float64,2}:
  1.0   4.0   9.0
 16.0  25.0  36.0

In [12]:
arr.^0.5 # elementwise exponent operator is .*

2×3 Array{Float64,2}:
 1.0  1.41421  1.73205
 2.0  2.23607  2.44949

In [13]:
arr+arr

2×3 Array{Float64,2}:
 2.0   4.0   6.0
 8.0  10.0  12.0

In [14]:
arr2 = [[0. 4. 1.]; [7. 2. 12.]]

2×3 Array{Float64,2}:
 0.0  4.0   1.0
 7.0  2.0  12.0

In [15]:
println(arr2 .> arr, " ") #elementwise greater than comparison.


Bool[false true false; true false true] 


In [16]:
println(arr2 == arr, "   ", arr2 .== arr) #equal comparisons

false   Bool[false false false; false false false]


## Array Slices and indexing

In [17]:
arr = Array(range(0, stop =10, step = 1))
println(arr)
println(arr[5])
println(arr[5:8])
arr[5:8] .= 12  #elementwise assigning values to slice
println(arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
4
[4, 5, 6, 7]
[0, 1, 2, 3, 12, 12, 12, 12, 8, 9, 10]


In [18]:
# If an array or slice of an array is assigned to a variable, the variable is a new copy of the array object
# It is not a copy

array_slice = arr[5:8]
array_slice[1] = 555
println(array_slice)
println(arr)

[555, 12, 12, 12]
[0, 1, 2, 3, 12, 12, 12, 12, 8, 9, 10]


### Boolean Indexing

In [50]:
NamesData = ["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"]
print(NamesData)
random_array =  rand(7,4)*2


["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"]

7×4 Array{Float64,2}:
 1.78091   0.797176  0.556539  1.57085 
 0.868632  0.595073  0.557916  0.158866
 1.71093   0.877603  0.237144  1.43598 
 1.62893   1.71348   1.78007   0.723781
 1.64802   0.35745   1.01054   1.32469 
 1.75653   1.02066   1.74336   1.25797 
 1.52091   1.71977   1.86851   0.809427

In [51]:
NamesFilter = NamesData .== "Joe"     #Elementwise array comparison
NamesFilter

7-element BitArray{1}:
 false
  true
 false
 false
 false
  true
  true

In [52]:
random_array[NamesFilter,:]

3×4 Array{Float64,2}:
 0.868632  0.595073  0.557916  0.158866
 1.75653   1.02066   1.74336   1.25797 
 1.52091   1.71977   1.86851   0.809427

In [53]:
random_array[NamesFilter,2:3]

3×2 Array{Float64,2}:
 0.595073  0.557916
 1.02066   1.74336 
 1.71977   1.86851 

In [54]:
random_array[.!NamesFilter,:]   #Negate the Boolean values.

4×4 Array{Float64,2}:
 1.78091  0.797176  0.556539  1.57085 
 1.71093  0.877603  0.237144  1.43598 
 1.62893  1.71348   1.78007   0.723781
 1.64802  0.35745   1.01054   1.32469 

In [55]:
NamesFilter = (NamesData .== "Will") .| (NamesData .== "Bob")   #Elementwise array comparison, must use parentheses
NamesFilter

7-element BitArray{1}:
  true
 false
  true
  true
  true
 false
 false

In [56]:
MatrixFilter = random_array.>1

7×4 BitArray{2}:
  true  false  false   true
 false  false  false  false
  true  false  false   true
  true   true   true  false
  true  false   true   true
  true   true   true   true
  true   true   true  false

In [73]:
random_array[random_array .> 1] .= 1   #elemetwise, replace values on the original object.
random_array 


7×4 Array{Float64,2}:
 1.0       1.0       1.0       1.0     
 0.868632  0.595073  0.557916  0.158866
 1.0       1.0       1.0       1.0     
 1.0       1.0       1.0       1.0     
 1.0       1.0       1.0       1.0     
 1.0       1.0       1.0       1.0     
 1.0       1.0       1.0       0.809427

In [74]:
random_array[NamesFilter,:] .=7
random_array


7×4 Array{Float64,2}:
 7.0       7.0       7.0       7.0     
 0.868632  0.595073  0.557916  0.158866
 7.0       7.0       7.0       7.0     
 7.0       7.0       7.0       7.0     
 7.0       7.0       7.0       7.0     
 1.0       1.0       1.0       1.0     
 1.0       1.0       1.0       0.809427

### Fancy Indexing

In [76]:
FancyArray = Array{Float64}(undef, (8, 4))
FancyArray

8×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [87]:
for i in 1:8
    FancyArray[i,:] .= i
end
FancyArray

8×4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 2.0  2.0  2.0  2.0
 3.0  3.0  3.0  3.0
 4.0  4.0  4.0  4.0
 5.0  5.0  5.0  5.0
 6.0  6.0  6.0  6.0
 7.0  7.0  7.0  7.0
 8.0  8.0  8.0  8.0

In [94]:
FancyArray[[4, 3, 1, 6],:]

4×4 Array{Float64,2}:
 4.0  4.0  4.0  4.0
 3.0  3.0  3.0  3.0
 1.0  1.0  1.0  1.0
 6.0  6.0  6.0  6.0

In [119]:
FancyArray[end:-3:2,:]   # Indexing from the end with negative numbers doesn't work. Instead, use reverse indexing. 

3×4 Array{Float64,2}:
 8.0  8.0  8.0  8.0
 5.0  5.0  5.0  5.0
 2.0  2.0  2.0  2.0

In [85]:
FancyArray[[1,3],[2,3]]

2×2 Array{Float64,2}:
 1.0  1.0
 3.0  3.0

In [86]:
FancyArray[[2,1],[2,3]]

2×2 Array{Float64,2}:
 2.0  2.0
 1.0  1.0

In [121]:
reshape(FancyArray,4,8)

4×8 Array{Float64,2}:
 1.0  5.0  1.0  5.0  1.0  5.0  1.0  5.0
 2.0  6.0  2.0  6.0  2.0  6.0  2.0  6.0
 3.0  7.0  3.0  7.0  3.0  7.0  3.0  7.0
 4.0  8.0  4.0  8.0  4.0  8.0  4.0  8.0

In [122]:
FancyArray

8×4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 2.0  2.0  2.0  2.0
 3.0  3.0  3.0  3.0
 4.0  4.0  4.0  4.0
 5.0  5.0  5.0  5.0
 6.0  6.0  6.0  6.0
 7.0  7.0  7.0  7.0
 8.0  8.0  8.0  8.0

### Transposing Arrays and Swapping Axes

In [140]:
using LinearAlgebra

In [151]:
TArray = transpose(FancyArray)

4×8 Transpose{Float64,Array{Float64,2}}:
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0

In [158]:
*(TArray, FancyArray)                  #Matrix inner product

4×4 Array{Float64,2}:
 204.0  204.0  204.0  204.0
 204.0  204.0  204.0  204.0
 204.0  204.0  204.0  204.0
 204.0  204.0  204.0  204.0

In [159]:
dot(TArray, FancyArray)               #Scalar inner product


680.0

In [195]:
ThreeAxesArray = reshape(collect(1:16),2,4,2)            #That doesn't work as expected.
println(ThreeAxesArray)

println(permutedims(ThreeAxesArray,[3,2,1]))

[1 3 5 7; 2 4 6 8]

[9 11 13 15; 10 12 14 16]
[1 3 5 7; 9 11 13 15]

[2 4 6 8; 10 12 14 16]


In [176]:
println(1:16)

1:16


In [227]:
array_transposing = transpose(reshape(collect(1:16),16,1))    #This seems more complex than it should
array_transposing2 = reshape(array_transposing,4,2,2)
array_transposing3 = permutedims(array_transposing2,[2,1,3])

2×4×2 Array{Int64,3}:
[:, :, 1] =
 1  2  3  4
 5  6  7  8

[:, :, 2] =
  9  10  11  12
 13  14  15  16

In [232]:
permutedims(array_transposing3,[2,1,3])                   #Like Swapaxes in Python, but more explict.

4×2×2 Array{Int64,3}:
[:, :, 1] =
 1  5
 2  6
 3  7
 4  8

[:, :, 2] =
  9  13
 10  14
 11  15
 12  16

## Universal Functions: Fast Element-Wise Array Functions

In [253]:
arr = collect(1:9)                
println(sqrt.(arr))                        #to apply the fucntion elementwise, use .() not just ()
println(exp.(arr))

[1.0, 1.41421, 1.73205, 2.0, 2.23607, 2.44949, 2.64575, 2.82843, 3.0]
[2.71828, 7.38906, 20.0855, 54.5982, 148.413, 403.429, 1096.63, 2980.96, 8103.08]


In [264]:
x = rand(8)
y = rand(8)
println(x)
println(y)
println(maximum(x))                     #maximum element of the array
println(max(x,y))                       #Compare the arrays, pairwise.

[0.789535, 0.59108, 0.709367, 0.579059, 0.287603, 0.613423, 0.420949, 0.249038]
[0.987309, 0.220914, 0.987049, 0.948659, 0.796013, 0.323365, 0.310519, 0.119909]
0.7895345124820878
[0.987309, 0.220914, 0.987049, 0.948659, 0.796013, 0.323365, 0.310519, 0.119909]


In [298]:
remainder, whole = modf.(2x)
println(remainder)
println(whole)

MethodError: MethodError: no method matching one(::Array{Float64,1})
Closest candidates are:
  one(!Matched::Missing) at missing.jl:83
  one(!Matched::BitArray{2}) at bitarray.jl:400
  one(!Matched::Type{T<:Number}) where T<:Number at number.jl:297
  ...

In [301]:
println(modf.(2x))

Tuple{Float64,Float64}[(0.579069, 1.0), (0.182161, 1.0), (0.418734, 1.0), (0.158119, 1.0), (0.575206, 0.0), (0.226845, 1.0), (0.841898, 0.0), (0.498076, 0.0)]


In [340]:
remainder = [y[1] for y in modf.(2x)]                  
whole = [y[2] for y in modf.(2x)]
println(remainder)
println(whole)

[0.579069, 0.182161, 0.418734, 0.158119, 0.575206, 0.226845, 0.841898, 0.498076]
[1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0]


In [343]:
remainder, whole = modf.(2x)                  #modf returns an array of tuples, python returns 2 arrays
println(remainder)
println(whole)

(0.5790690249641757, 1.0)
(0.18216096628219125, 1.0)
