In [1]:
import numpy as np
import matplotlib as plt


In [2]:
data = np.random.randn(2,3)
data


array([[ 1.14585155,  0.43297267,  0.48354314],
       [-1.12670139, -0.64553391, -0.36871637]])

In [3]:
data*10

array([[ 11.45851554,   4.3297267 ,   4.83543138],
       [-11.26701387,  -6.45533912,  -3.6871637 ]])

In [4]:
data + data

array([[ 2.29170311,  0.86594534,  0.96708628],
       [-2.25340277, -1.29106782, -0.73743274]])

## Creating ndarrays


Convert from lists to numpy array.

In [5]:
data1 = [4, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [6]:
arr1


array([ 4. ,  7.5,  8. ,  0. ,  1. ])

In [7]:
# 2 Dimensional Arrays
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2) 

In [8]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)


2
(2, 4)
int64


In [10]:
# Zero array
zeros = np.zeros((3,6) )
zeros

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [11]:
empty_array = np.empty((2,3,2))
empty_array

array([[[  2.31584178e+077,   2.00390251e+000],
        [  2.96439388e-323,   0.00000000e+000],
        [  2.12199579e-314,   5.64233733e-067]],

       [[  4.96925479e-091,   9.13442870e+169],
        [  3.61247494e+174,   2.37907810e+184],
        [  3.99910963e+252,   8.34404935e-309]]])

In [12]:
ordered_array = np.arange(15)
ordered_array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Arithmatic with ndarrays

In [13]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])


In [14]:
arr*arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [15]:
arr ** 2

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [16]:
arr ** .5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [17]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr2)
arr2 > arr

[[  0.   4.   1.]
 [  7.   2.  12.]]


array([[False,  True, False],
       [ True, False,  True]], dtype=bool)

## Array Slices and indexing


In [18]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print (arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [19]:
# If an array or slice of an array is assigned to a variable, the variable points to the original object
# It is not a copy

array_slice = arr[5:8]
array_slice[1] = 555
print(arr)


[  0   1   2   3   4  12 555  12   8   9]


### Boolean Indexing

In [20]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names
data

array([[-0.70635445,  2.02942134, -0.03415327, -0.47056091],
       [-0.13158814, -1.66269761,  0.51027341, -0.61711074],
       [-0.02289441, -0.5196267 , -1.51879282,  1.44347978],
       [ 0.09672557,  0.03817493, -1.07727432, -1.41220722],
       [ 0.0108547 ,  1.11822062,  1.46482032, -0.11193357],
       [-0.35942941, -1.51842586,  0.2587478 , -0.40714706],
       [-2.46125043, -0.77666528, -0.28688376, -1.37004505]])

In [21]:
BoolFilter = names == 'Joe'

In [22]:
BoolFilter

array([False,  True, False, False, False,  True,  True], dtype=bool)

In [23]:
data[BoolFilter]

array([[-0.13158814, -1.66269761,  0.51027341, -0.61711074],
       [-0.35942941, -1.51842586,  0.2587478 , -0.40714706],
       [-2.46125043, -0.77666528, -0.28688376, -1.37004505]])

In [24]:
data[BoolFilter,2:]

array([[ 0.51027341, -0.61711074],
       [ 0.2587478 , -0.40714706],
       [-0.28688376, -1.37004505]])

In [25]:
data[BoolFilter,3]

array([-0.61711074, -0.40714706, -1.37004505])

In [26]:
BoolFilter2 = names != 'Joe'
BoolFilter2

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [27]:
data[~BoolFilter2]

array([[-0.13158814, -1.66269761,  0.51027341, -0.61711074],
       [-0.35942941, -1.51842586,  0.2587478 , -0.40714706],
       [-2.46125043, -0.77666528, -0.28688376, -1.37004505]])

In [28]:
mask = (names == 'Joe') | (names == 'Will') #Union of filters.
print(mask)
data[mask]

[False  True  True False  True  True  True]


array([[-0.13158814, -1.66269761,  0.51027341, -0.61711074],
       [-0.02289441, -0.5196267 , -1.51879282,  1.44347978],
       [ 0.0108547 ,  1.11822062,  1.46482032, -0.11193357],
       [-0.35942941, -1.51842586,  0.2587478 , -0.40714706],
       [-2.46125043, -0.77666528, -0.28688376, -1.37004505]])

In [29]:
data[data < 0] = 0      #Replace Negative values, element wise
data

array([[ 0.        ,  2.02942134,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.51027341,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.44347978],
       [ 0.09672557,  0.03817493,  0.        ,  0.        ],
       [ 0.0108547 ,  1.11822062,  1.46482032,  0.        ],
       [ 0.        ,  0.        ,  0.2587478 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [30]:
data[BoolFilter] = 0      #Replace values, based on boolean filter
data

array([[ 0.        ,  2.02942134,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.44347978],
       [ 0.09672557,  0.03817493,  0.        ,  0.        ],
       [ 0.0108547 ,  1.11822062,  1.46482032,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

### Fancy Indexing

In [31]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [32]:
arr[[4, 3, 0, 6]]    #Pass a list as the index to select and sort original matrix


array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [33]:
arr[[-3, -5, -7]]     #Pass a list as the index to select and sort original matrix, use negatives to select from the end of the array matrix



array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [34]:
arr = np.arange(32).reshape((8, 4))
print(arr)
arr[[1, 5, 7, 2], [0, 3, 1, 2]]    #pass 2 lists, return values from paired indices.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([ 4, 23, 29, 10])

In [35]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]    #The first list selects the rows, the second list reorders the row.

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Transposing Arrays and Swapping Axes

In [36]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [37]:
for i in range(1,9):
    print(i)

1
2
3
4
5
6
7
8


In [38]:
arr = np.empty((8, 4))
for i in range(1,9):
    arr[i-1] = i
print(arr)
np.dot(arr.T, arr)

[[ 1.  1.  1.  1.]
 [ 2.  2.  2.  2.]
 [ 3.  3.  3.  3.]
 [ 4.  4.  4.  4.]
 [ 5.  5.  5.  5.]
 [ 6.  6.  6.  6.]
 [ 7.  7.  7.  7.]
 [ 8.  8.  8.  8.]]


array([[ 204.,  204.,  204.,  204.],
       [ 204.,  204.,  204.,  204.],
       [ 204.,  204.,  204.,  204.],
       [ 204.,  204.,  204.,  204.]])

In [39]:
arr = np.arange(16).reshape((2, 2, 4))
print(arr)
arr.transpose((1, 0, 2))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [40]:
arr
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

### Expressing Conditional Logic as Array Operations

In [41]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [42]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

[1.1000000000000001, 2.2000000000000002, 1.3, 1.3999999999999999, 2.5]

In [43]:
result = np.where(cond, xarr, yarr)            #Arrays must be the same shape
result

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [44]:
arr = np.random.randn(4, 4)
arr
arr > 0
np.where(arr > 0, 2, -2)

array([[ 2, -2,  2, -2],
       [ 2, -2, -2,  2],
       [ 2,  2, -2,  2],
       [-2,  2, -2,  2]])

In [45]:
np.where(arr > 0, 2, arr) # set only positive values to 2

array([[ 2.        , -0.4334927 ,  2.        , -0.78635983],
       [ 2.        , -1.07799753, -0.5892145 ,  2.        ],
       [ 2.        ,  2.        , -1.67218734,  2.        ],
       [-0.82872236,  2.        , -0.75744131,  2.        ]])

In [49]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = np.where(cond, xarr, yarr)
result

ValueError: operands could not be broadcast together with shapes (4,) (5,) (5,) 