## Julia notation for setting up arrays and some notations

In [21]:
random_array =  rand(2,3)
println(random_array)
println(random_array *10)
println(random_array + random_array)

[0.626782 0.874963 0.183308; 0.168988 0.750467 0.122164]
[6.26782 8.74963 1.83308; 1.68988 7.50467 1.22164]
[1.25356 1.74993 0.366617; 0.337977 1.50093 0.244328]


## Creating arrays. 

In [27]:
data1 = [4, 7.5, 8, 0, 1]
#arr1 = array(data1)

5-element Array{Float64,1}:
 4.0
 7.5
 8.0
 0.0
 1.0

In [28]:
println(data1)

[4.0, 7.5, 8.0, 0.0, 1.0]


### 2 Dimensional Arrays

In [46]:
data2 = [[1 2 3 4];[5 6 7 8]]

2×4 Array{Int64,2}:
 1  2  3  4
 5  6  7  8

In [50]:
println(ndims(data2)) # Dimensions
println(size(data2)) # Shape of the array/matrix
println(eltype(data2)) #data type of elements


2
(2, 4)
Int64


#### Calling the variable without a print statement returns the descriptive information, as well.  

In [49]:
data2

2×4 Array{Int64,2}:
 1  2  3  4
 5  6  7  8

#### Zero array

In [55]:
zeros_matrix = zeros(3,6)
println(zeros_matrix)
zeros_matrix

[0.0 0.0 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0 0.0; 0.0 0.0 0.0 0.0 0.0 0.0]


3×6 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

#### Empty Array

In [65]:
empty_array = Array{Float64}(undef, (3, 2,2))
empty_array

3×2×2 Array{Float64,3}:
[:, :, 1] =
 2.34631e-314  2.34631e-314
 2.34631e-314  2.34631e-314
 2.34631e-314  2.34631e-314

[:, :, 2] =
 2.34631e-314  2.34631e-314
 2.34631e-314  2.34631e-314
 2.34631e-314  0.0         

In [79]:
ordered_array = Array(range(0, stop =14, step = 1))
println(ordered_array)



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]


## Arithmatic with arrays

In [83]:
arr = [[1. 2. 3.];[4. 5. 6.]]

2×3 Array{Float64,2}:
 1.0  2.0  3.0
 4.0  5.0  6.0

In [87]:
arr.*arr # elementwise multiplcation operator is .*

2×3 Array{Float64,2}:
  1.0   4.0   9.0
 16.0  25.0  36.0

In [90]:
arr.^0.5 # elementwise exponent operator is .*

2×3 Array{Float64,2}:
 1.0  1.41421  1.73205
 2.0  2.23607  2.44949

In [93]:
arr+arr

2×3 Array{Float64,2}:
 2.0   4.0   6.0
 8.0  10.0  12.0

In [113]:
arr2 = [[0. 4. 1.]; [7. 2. 12.]]

2×3 Array{Float64,2}:
 0.0  4.0   1.0
 7.0  2.0  12.0

In [110]:
println(arr2 .> arr, " ") #elementwise greater than comparison.


Bool[false true false; true false true] 


In [116]:
println(arr2 == arr, "   ", arr2 .== arr) #equal comparisons

false   Bool[false false false; false false false]


## Array Slices and indexing

In [5]:
arr = Array(range(0, stop =10, step = 1))
println(arr)
println(arr[5])
println(arr[5:8])
arr[5:8] .= 12  #elementwise assigning values to slice
println(arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
4
[4, 5, 6, 7]
[0, 1, 2, 3, 12, 12, 12, 12, 8, 9, 10]


In [8]:
# If an array or slice of an array is assigned to a variable, the variable is a new copy of the array object
# It is not a copy

array_slice = arr[5:8]
array_slice[1] = 555
println(array_slice)
println(arr)

[555, 12, 12, 12]
[0, 1, 2, 3, 12, 12, 12, 12, 8, 9, 10]
