In [1]:
import numpy as np
import matplotlib as plt


In [2]:
data = np.random.randn(2,3)
data


array([[-1.76154643, -0.98686019,  1.17419617],
       [ 0.62066353,  1.47620032, -0.96469454]])

In [3]:
data*10

array([[-17.61546432,  -9.86860191,  11.74196172],
       [  6.20663534,  14.76200321,  -9.64694543]])

In [4]:
data + data

array([[-3.52309286, -1.97372038,  2.34839234],
       [ 1.24132707,  2.95240064, -1.92938909]])

## Creating ndarrays


Convert from lists to numpy array.

In [5]:
data1 = [4, 7.5, 8, 0, 1]
arr1 = np.array(data1)

In [6]:
arr1


array([ 4. ,  7.5,  8. ,  0. ,  1. ])

In [7]:
# 2 Dimensional Arrays
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2) 

In [8]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)


2
(2, 4)
int64


In [10]:
# Zero array
zeros = np.zeros((3,6) )
zeros

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [11]:
empty_array = np.empty((2,3,2))
empty_array

array([[[  1.72723371e-077,   2.68678094e+154],
        [  2.96439388e-323,   0.00000000e+000],
        [  2.19600298e-314,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  2.19600297e-314,   2.19600297e-314],
        [  0.00000000e+000,   8.34402697e-309]]])

In [12]:
ordered_array = np.arange(15)
ordered_array


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Arithmatic with ndarrays

In [13]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])


In [14]:
arr*arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [15]:
arr ** 2

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [16]:
arr ** .5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [17]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr2)
arr2 > arr

[[  0.   4.   1.]
 [  7.   2.  12.]]


array([[False,  True, False],
       [ True, False,  True]], dtype=bool)

## Array Slices and indexing


In [18]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print (arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [19]:
# If an array or slice of an array is assigned to a variable, the variable points to the original object
# It is not a copy

array_slice = arr[5:8]
array_slice[1] = 555
print(arr)


[  0   1   2   3   4  12 555  12   8   9]


### Boolean Indexing

In [20]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names
data

array([[ 1.46209745,  1.51854674,  0.67096531,  0.2804948 ],
       [ 0.12351893,  1.4811696 ,  0.39413527,  1.04924266],
       [ 0.58211088,  0.03320589, -1.16879027,  0.67791231],
       [ 0.71309037,  0.28518614,  0.06572241, -2.21584918],
       [-0.75531035, -0.95707078, -1.79333757,  0.59463902],
       [ 0.05081544,  0.34051357, -0.48111174, -0.02169502],
       [ 1.131491  ,  0.85801387, -3.01862058,  0.17597125]])

In [24]:
BoolFilter = names == 'Joe'

In [25]:
BoolFilter

array([False,  True, False, False, False,  True,  True], dtype=bool)

In [26]:
data[BoolFilter]

array([[ 0.12351893,  1.4811696 ,  0.39413527,  1.04924266],
       [ 0.05081544,  0.34051357, -0.48111174, -0.02169502],
       [ 1.131491  ,  0.85801387, -3.01862058,  0.17597125]])

In [27]:
data[BoolFilter,2:]

array([[ 0.39413527,  1.04924266],
       [-0.48111174, -0.02169502],
       [-3.01862058,  0.17597125]])

In [28]:
data[BoolFilter,3]

array([ 1.04924266, -0.02169502,  0.17597125])

In [29]:
BoolFilter2 = names != 'Joe'
BoolFilter2

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [30]:
data[~BoolFilter2]

array([[ 0.12351893,  1.4811696 ,  0.39413527,  1.04924266],
       [ 0.05081544,  0.34051357, -0.48111174, -0.02169502],
       [ 1.131491  ,  0.85801387, -3.01862058,  0.17597125]])

In [33]:
mask = (names == 'Joe') | (names == 'Will') #Union of filters.
print(mask)
data[mask]

[False  True  True False  True  True  True]


array([[ 0.12351893,  1.4811696 ,  0.39413527,  1.04924266],
       [ 0.58211088,  0.03320589, -1.16879027,  0.67791231],
       [-0.75531035, -0.95707078, -1.79333757,  0.59463902],
       [ 0.05081544,  0.34051357, -0.48111174, -0.02169502],
       [ 1.131491  ,  0.85801387, -3.01862058,  0.17597125]])

In [34]:
data[data < 0] = 0      #Replace Negative values, element wise
data

array([[ 1.46209745,  1.51854674,  0.67096531,  0.2804948 ],
       [ 0.12351893,  1.4811696 ,  0.39413527,  1.04924266],
       [ 0.58211088,  0.03320589,  0.        ,  0.67791231],
       [ 0.71309037,  0.28518614,  0.06572241,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.59463902],
       [ 0.05081544,  0.34051357,  0.        ,  0.        ],
       [ 1.131491  ,  0.85801387,  0.        ,  0.17597125]])

In [36]:
data[BoolFilter] = 0      #Replace values, based on boolean filter
data

array([[ 1.46209745,  1.51854674,  0.67096531,  0.2804948 ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.58211088,  0.03320589,  0.        ,  0.67791231],
       [ 0.71309037,  0.28518614,  0.06572241,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.59463902],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

### Fancy Indexing

In [37]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [39]:
arr[[4, 3, 0, 6]]    #Pass a list as the index to select and sort original matrix


array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [40]:
arr[[-3, -5, -7]]     #Pass a list as the index to select and sort original matrix, use negatives to select from the end of the array matrix



array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [42]:
arr = np.arange(32).reshape((8, 4))
print(arr)
arr[[1, 5, 7, 2], [0, 3, 1, 2]]    #pass 2 lists, return values from paired indices.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([ 4, 23, 29, 10])

In [44]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]    #The first list selects the rows, the second list reorders the row.

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

### Transposing Arrays and Swapping Axes

In [47]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [48]:
arr = np.random.randn(6, 3)
print(arr)
np.dot(arr.T, arr)

[[-1.15834173  0.07168037  0.7774395 ]
 [ 0.56586207 -0.40157488  1.04468656]
 [ 0.18994703  0.07197332 -1.88797499]
 [-0.47810467 -1.09140515  0.49952906]
 [-0.98278589  0.29608317  0.63100822]
 [ 0.40336564  0.16648209  0.47356587]]


array([[  3.05519135e+00,   1.37745654e-03,  -1.33596032e+00],
       [  1.37745654e-03,   1.47812734e+00,  -7.79193997e-01],
       [ -1.33596032e+00,  -7.79193997e-01,   6.13219704e+00]])

In [49]:
arr = np.arange(16).reshape((2, 2, 4))
print(arr)
arr.transpose((1, 0, 2))

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [50]:
arr
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])